apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:masters
      rolearn: arn:aws:iam::328730416000:role/UdacityFlaskDeployCBKubectlRole
      username: build
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::328730416000:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-1LBX11BXYG9SN
      username: system:node:{{EC2PrivateDNSName}}


kind: ConfigMap
metadata:
  creationTimestamp: "2021-09-14T14:28:33Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1251"
  uid: 0c25e896-cd7f-48f9-ae1a-1ef805d16a09