apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::328730416000:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-QHXNSV86E9EP
      username: system:node:{{EC2PrivateDNSName}}
      - system:masters
      rolearn: arn:aws:iam::328730416000:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2021-09-13T13:03:34Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1699"
  uid: 3dff7ac0-6ab1-4497-bd23-c69286af6212
